defaults: &defaults
    jira_url: http://192.168.20.1:8080/jira/
    dept_root_name: 研发中心
    genders:
        - m
        - f
    marriage_status:
        - unknown
        - married
        - single 
        - divorced
    history_categories:
        - profile
        - orgnizational
        - review
        - award
        - employment
        - talk
    employment_status:
        - normal
        - on leave
        - outsourced
        - fired
        - left
    employment_not_here_status:
        - outsourced
        - fired
        - left        
    employment_left_enum:
        - fired
        - left        
    employment_change_reasons:
        - hire as
        - promotion
        - demotion
        - fired
        - left
        - rejoin
    filters:
        none: 
        manage:
            employment_state:
                - normal 
                - on leave
                - outsourced
        amanage:
            employment_state:
                - normal
                - on leave
        work:
            employment_state:
                - normal
        left:
            employment_state:
                - fired
                - left
        
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults